require('plugins')
require('settings')

require('plugins/neotree')
require('plugins/telescope')
require('plugins/treesitter')
require('plugins/lsp')
require('plugins/cmp')
require('plugins/lualine')
require('plugins/bufferline')
require('plugins/registers')
