require("plugins")

require("settings")
require("keybinds")

require("configs/compe")
require("configs/bufferline")
require("configs/lsp")
require("configs/treesitter")
require("configs/lualine")
require("configs/telescope")
require("configs/autotag")
require("configs/comment")
require("configs/dressing")
require("configs/terminal")
