onboarding = false

[keys]
prefix = "ctrl+a"
resize_mode = ""
reload_config = "prefix+r"
goto = "prefix+w"
next_tab = ""
last_pane = "prefix+tab"
cycle_pane_next = ""
cycle_pane_previous = ""
detach = "prefix+d"
split_vertical = "prefix+%"
split_horizontal = "prefix+\""
zoom = "prefix+z"
toggle_sidebar = "prefix+e"
new_workspace = "prefix+n"
workspace_picker = "prefix+s"
navigate_workspace_up = "k"
navigate_workspace_down = "j"

[terminal]
new_cwd = "follow"

[theme]
name = "catppuccin"

[ui]
host_cursor = "native"
mouse_scroll_lines = 1
prompt_new_tab_name = false
pane_borders = false
pane_gaps = false
accent = "magenta"
agent_panel_sort = "priority"

[ui.sound]
enabled = false

[ui.toast]
delivery = "off"

[experimental]
kitty_graphics = true
