import = ["/Users/tom/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]

[font]
size = 15.5

[font.normal]
family = "JetbrainsMono Nerd Font"

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"

[window.padding]
x = 6
y = 6

[keyboard]
bindings = [
    { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
    { key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~" },
]
